# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Short and clear title describing the task.', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what needs to be done.', verbose_name='description')),
                ('position', models.CharField(blank=True, default='', help_text='Fractional index for ordering within its current status.', max_length=100, verbose_name='position')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level used to organize or escalate tasks.', max_length=10, verbose_name='priority')),
                ('origin', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', help_text='Defines whether the task was created internally or requested externally.', max_length=10, verbose_name='origin')),
                ('deadline', models.DateField(blank=True, help_text='Optional due date for the task.', null=True, verbose_name='deadline')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp automatically filled when the task is completed.', null=True, verbose_name='completed at')),
                ('assignees', models.ManyToManyField(blank=True, help_text='Users responsible for executing this task.', related_name='tasks', to='workplace.workplacemember', verbose_name='assignees')),
                ('created_by', models.ForeignKey(help_text='User who created the task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='workplace.workplacemember', verbose_name='created by')),
                ('workplace', models.ForeignKey(blank=True, help_text='The workplace this task belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='The title of the subtask.', max_length=200, verbose_name='title')),
                ('is_done', models.BooleanField(default=False, help_text='Whether the subtask is completed.', verbose_name='is done')),
                ('position', models.CharField(blank=True, default='', help_text='Fractional index for ordering within the parent task.', max_length=100, verbose_name='position')),
                ('assignee', models.ForeignKey(blank=True, help_text='The member responsible for this subtask.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplace.workplacemember', verbose_name='assignee')),
                ('task', models.ForeignKey(help_text='The parent task for this subtask.', on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='task.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='The name of the status.', max_length=50, verbose_name='name')),
                ('color', models.CharField(default='#5CFCD4', help_text='Hexadecimal color code for the status.', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon identifier for the status (e.g. i-lucide-circle-dashed).', max_length=50, verbose_name='icon')),
                ('category', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], help_text='Fixed category used to derive workflow semantics (todo/in progress/done/cancelled).', max_length=20, verbose_name='category')),
                ('position', models.CharField(blank=True, default='', help_text='Fractional index for ordering within its workplace.', max_length=100, verbose_name='position')),
                ('workplace', models.ForeignKey(blank=True, help_text='The workplace this status belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Current workplace status of the task.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task.taskstatus', verbose_name='status'),
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='The name of the tag.', max_length=50, verbose_name='name')),
                ('color', models.CharField(default='#5CFCD4', help_text='Hexadecimal color code for the tag.', max_length=7, verbose_name='color')),
                ('workplace', models.ForeignKey(blank=True, help_text='The workplace this tag belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags used to categorize or group this task.', related_name='tasks', to='task.tasktag', verbose_name='tags'),
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='The name of the type.', max_length=50, verbose_name='name')),
                ('color', models.CharField(default='#5CFCD4', help_text='Hexadecimal color code for the type.', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, default='', help_text='Icon identifier for the type (e.g. i-lucide-palette).', max_length=50, verbose_name='icon')),
                ('position', models.CharField(blank=True, default='', help_text='Fractional index for ordering within its workplace.', max_length=100, verbose_name='position')),
                ('workplace', models.ForeignKey(blank=True, help_text='The workplace this type belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Task Types',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Category of the task.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='task.tasktype', verbose_name='type'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workplace', 'deleted_at'], name='task_task_workpla_7d40f3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workplace', 'status', 'deleted_at'], name='task_task_workpla_001300_idx'),
        ),
    ]
