# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('workplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, help_text='The title of the media deliverable.', max_length=255, verbose_name='title')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the media.', verbose_name='notes')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Video'), (3, 'Document'), (4, 'Art')], default=4, help_text='The type of media (image, video, document, art).', verbose_name='type')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether this media has been approved by the requester.', verbose_name='is approved')),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Public token used for sharing the media with external stakeholders.', unique=True, verbose_name='share token')),
                ('designer', models.ForeignKey(help_text='The designer who produced this media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_medias', to=settings.AUTH_USER_MODEL, verbose_name='designer')),
                ('task', models.ForeignKey(blank=True, help_text='The task this media belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='task.task', verbose_name='task')),
                ('workplace', models.ForeignKey(blank=True, help_text='The workplace this media belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'art_art',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='The version number (e.g., 1, 2, 3).', verbose_name='number')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Video'), (3, 'File'), (4, 'Link'), (5, 'Text'), (6, 'Document')], default=1, help_text='The type of file for this version.', verbose_name='type')),
                ('drive_file_id', models.CharField(blank=True, help_text='Google Drive file ID.', max_length=255, verbose_name='Drive file ID')),
                ('drive_url', models.URLField(blank=True, help_text='Direct view/download URL from Google Drive.', max_length=500, verbose_name='Drive URL')),
                ('file_name', models.CharField(blank=True, help_text='Original file name.', max_length=255, verbose_name='file name')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file.', max_length=127, verbose_name='MIME type')),
                ('text_content', models.TextField(blank=True, default='', help_text='Raw text content for text-type versions, edited directly in the app.', verbose_name='text content')),
                ('media', models.ForeignKey(help_text='The media this version belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='media.media', verbose_name='media')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'db_table': 'art_artversion',
                'ordering': ['-number'],
                'unique_together': {('media', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.TextField(help_text='The content of the comment.', verbose_name='content')),
                ('block_index', models.PositiveSmallIntegerField(blank=True, help_text='Position anchor for the comment, meaning depends on media type — e.g. a timestamp in seconds for video versions. Null means a general (non-anchored) comment.', null=True, verbose_name='block index')),
                ('quote', models.TextField(blank=True, default='', help_text='The selected text snippet this comment is anchored to, for text versions. Blank means a general comment.', verbose_name='quote')),
                ('author', models.ForeignKey(blank=True, help_text='The user who wrote the comment.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('media', models.ForeignKey(help_text='The media being commented on.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media.media', verbose_name='media')),
                ('version', models.ForeignKey(blank=True, help_text='The specific version being commented on, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media.mediaversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'art_artcomment',
            },
        ),
        migrations.CreateModel(
            name='MediaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('decision', models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike')], default=1, help_text='The feedback decision (like or dislike).', verbose_name='decision')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or reasons for the feedback.', verbose_name='notes')),
                ('given_by', models.ForeignKey(help_text='The user who gave the feedback.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='given by')),
                ('media', models.ForeignKey(help_text='The media receiving feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='media.media', verbose_name='media')),
                ('version', models.ForeignKey(blank=True, help_text='The specific version receiving feedback, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='media.mediaversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'art_artfeedback',
                'unique_together': {('media', 'version', 'given_by')},
            },
        ),
    ]
