# Generated by Django 6.1 on 2026-09-10 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediacomment",
            name="guest_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display name for a comment left through the public share link, where there's no authenticated user to attribute it to. Blank whenever `author` is set.",
                max_length=150,
                verbose_name="guest name",
            ),
        ),
        migrations.AlterField(
            model_name="mediacomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who wrote the comment. Null for a comment left through the public share link.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="mediafeedback",
            name="given_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who gave the feedback. Null for feedback left through the public share link — unlike the authenticated path, there's no stable identity to dedupe on, so each anonymous vote is its own row (the unique constraint below only applies between non-null values).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="given by",
            ),
        ),
    ]
