# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('workplace', 'Workplace')], default='private', help_text='Who can see this sticky.', max_length=20, verbose_name='visibility')),
                ('color', models.CharField(default='#FEE440', help_text='Hexadecimal color code for the sticky.', max_length=7, verbose_name='color')),
                ('text', models.TextField(blank=True, help_text='The sticky content.', verbose_name='text')),
                ('position', models.CharField(blank=True, default='', help_text='Fractional index for ordering stickies.', max_length=100, verbose_name='position')),
                ('created_by', models.ForeignKey(help_text='User who created this sticky.', on_delete=django.db.models.deletion.CASCADE, related_name='created_stickies', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('workplace', models.ForeignKey(help_text='The workplace this sticky belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='stickies', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Sticky',
                'verbose_name_plural': 'Stickies',
                'abstract': False,
                'indexes': [models.Index(fields=['workplace', 'deleted_at'], name='sticky_stic_workpla_90e48d_idx'), models.Index(fields=['workplace', 'visibility', 'deleted_at'], name='sticky_stic_workpla_ee2d35_idx'), models.Index(fields=['workplace', 'created_by', 'deleted_at'], name='sticky_stic_workpla_a41026_idx')],
            },
        ),
    ]
