# Generated by Django 6.1 on 2026-09-16 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sticky',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this sticky.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_stickies', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
    ]
