# Generated by Django 6.1 on 2026-09-16 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short label shown on the Home page.', max_length=100, verbose_name='title')),
                ('url', models.URLField(help_text="The link's destination.", verbose_name='url')),
                ('icon', models.CharField(blank=True, help_text='Optional Lucide icon name shown next to the title.', max_length=100, verbose_name='icon')),
                ('created_by', models.ForeignKey(help_text='Member who added this quicklink.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quicklinks', to='workplace.workplacemember', verbose_name='created by')),
                ('workplace', models.ForeignKey(help_text='The workplace this quicklink belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='quicklinks', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Quicklink',
                'verbose_name_plural': 'Quicklinks',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['workplace', 'created_at'], name='quicklink_q_workpla_17d818_idx')],
            },
        ),
    ]
