# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'System'), (2, 'Order'), (3, 'Message'), (4, 'Task Assigned'), (5, 'Media Comment'), (6, 'Member Joined')], default=1, help_text='The type of the inbox notification.', verbose_name='type')),
                ('title', models.CharField(help_text='The title of the notification.', max_length=255, verbose_name='title')),
                ('message', models.TextField(help_text='The body content of the notification.', verbose_name='message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification.', verbose_name='is read')),
                ('member', models.ForeignKey(help_text='The workplace member who owns this inbox entry.', on_delete=django.db.models.deletion.CASCADE, related_name='inboxes', to='workplace.workplacemember', verbose_name='member')),
                ('sender', models.ForeignKey(blank=True, help_text='The workplace member who created this notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_inboxes', to='workplace.workplacemember', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'Inbox',
                'verbose_name_plural': 'Inboxes',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['member', 'is_read'], name='inbox_inbox_member__16917d_idx'), models.Index(fields=['type'], name='inbox_inbox_type_4a5749_idx')],
            },
        ),
    ]
