# Generated by Django 6.1 on 2026-09-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'System'), (2, 'Order'), (3, 'Message'), (4, 'Task Assigned'), (5, 'Media Comment'), (6, 'Member Joined'), (7, 'Member Join Requested')], default=1, help_text='The type of the inbox notification.', verbose_name='type'),
        ),
    ]
