# Generated by Django 6.1 on 2026-09-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_inbox_type'),
        ('workplace', '0002_workplacemember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='related_member',
            field=models.ForeignKey(blank=True, help_text='The membership this notification is about (e.g. a pending join request), if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workplace.workplacemember', verbose_name='related member'),
        ),
    ]
