# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lib.utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_style', models.CharField(blank=True, default='', help_text='CSS color/gradient or external image URL. Ignored when a cover file is set.', max_length=500, verbose_name='cover style')),
                ('cover_credit', models.JSONField(blank=True, help_text='Attribution for the cover style when its source requires it (Unsplash).', null=True, verbose_name='cover credit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('photo', models.ImageField(blank=True, help_text="The user's profile photo.", null=True, upload_to=lib.utils.upload.upload_to_path('profiles', 'photos'), verbose_name='photo')),
                ('cover', models.ImageField(blank=True, help_text="The user's profile cover image.", null=True, upload_to=lib.utils.upload.upload_to_path('profiles', 'covers'), verbose_name='cover')),
                ('user', models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'unique_together': {('user',)},
            },
        ),
    ]
