# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lib.utils.upload


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("task", "0001_initial"),
        ("workplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(help_text="The name of the type.", max_length=50, verbose_name="name")),
                (
                    "color",
                    models.CharField(
                        default="#5CFCD4",
                        help_text="Hexadecimal color code for the type.",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier for the type (e.g. i-lucide-palette).",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fractional index for ordering within its workplace.",
                        max_length=100,
                        verbose_name="position",
                    ),
                ),
                (
                    "default_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Starting markdown content used to seed a new document's first version when created with this type. Blank means the document starts empty.",
                        verbose_name="default content",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        help_text="The workplace this type belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_types",
                        to="workplace.workplace",
                        verbose_name="workplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cover_style",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CSS color/gradient or external image URL. Ignored when a cover file is set.",
                        max_length=500,
                        verbose_name="cover style",
                    ),
                ),
                (
                    "cover_credit",
                    models.JSONField(
                        blank=True,
                        help_text="Attribution for the cover style when its source requires it (Unsplash).",
                        null=True,
                        verbose_name="cover credit",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="The title of the document.", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier (e.g. i-lucide-file-text) or a literal emoji character.",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded banner image shown at the top of the document.",
                        null=True,
                        upload_to=lib.utils.upload.upload_to_path("documents", "covers"),
                        verbose_name="cover",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes about the document.", verbose_name="notes"),
                ),
                (
                    "folder",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Slash-separated vault folder path for this document (e.g. 'Clientes/Café Origem'). Blank means the document sits at the vault root.",
                        max_length=255,
                        verbose_name="folder",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("workplace", "Workplace")],
                        default="workplace",
                        help_text="Who besides the author and workplace admins can see this document: every workplace member, or nobody else.",
                        max_length=20,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "allow_member_edit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether workplace members who can view this document may also edit it (the author and workplace admins can always edit, regardless of this).",
                        verbose_name="allow member edit",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The user who created this document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="The task this document belongs to (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="task.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        help_text="The workplace this document belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="workplace.workplace",
                        verbose_name="workplace",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The type/category of this document.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="document.documenttype",
                        verbose_name="type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, help_text="The version number (e.g., 1, 2, 3).", verbose_name="number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        help_text="Draft versions are freely editable but cannot receive comments. Published versions are read-only until switched back to draft.",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=str,
                        help_text="The document content for this version, as a markdown string (supports '[[Title]]' wiki-links to other documents).",
                        verbose_name="content",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document this version belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="document.document",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
                "ordering": ["-number"],
                "unique_together": {("document", "number")},
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("content", models.TextField(help_text="The content of the comment.", verbose_name="content")),
                (
                    "block_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Line index in the version's content this comment is anchored to. Null means a general (non-anchored) comment.",
                        null=True,
                        verbose_name="block index",
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The selected text snippet this comment is anchored to, if any. Blank means a general comment.",
                        verbose_name="quote",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who wrote the comment.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document being commented on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="document.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific version being commented on, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="document.documentversion",
                        verbose_name="version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="DocumentFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "decision",
                    models.IntegerField(
                        choices=[(1, "Like"), (2, "Dislike")],
                        default=1,
                        help_text="The feedback decision (like or dislike).",
                        verbose_name="decision",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or reasons for the feedback.", verbose_name="notes"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document receiving feedback.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="document.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "given_by",
                    models.ForeignKey(
                        help_text="The user who gave the feedback.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="given by",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific version receiving feedback, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="document.documentversion",
                        verbose_name="version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
                "unique_together": {("document", "version", "given_by")},
            },
        ),
    ]
