# Generated by Django 6.1 on 2026-09-17 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('task', '0002_task_deleted_by'),
        ('workplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted the document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workplace', 'deleted_at'], name='document_do_workpla_ed9d9b_idx'),
        ),
    ]
