# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.db import migrations, models

import lib.utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.JSONField(help_text='The actual data submitted for this field.', verbose_name='value')),
            ],
            options={
                'verbose_name': 'Form Answer',
                'verbose_name_plural': 'Form Answers',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_style', models.CharField(blank=True, default='', help_text='CSS color/gradient or external image URL. Ignored when a cover file is set.', max_length=500, verbose_name='cover style')),
                ('cover_credit', models.JSONField(blank=True, help_text='Attribution for the cover style when its source requires it (Unsplash).', null=True, verbose_name='cover credit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='The title of the form.', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text="A detailed description of the form's purpose.", verbose_name='description')),
                ('is_published', models.BooleanField(default=False, help_text='Whether the form is publicly available.', verbose_name='is published')),
                ('cover_image', models.ImageField(blank=True, help_text='A cover image to be displayed at the top of the form.', null=True, upload_to=lib.utils.upload.upload_to_path('forms', 'covers'), verbose_name='cover image')),
                ('require_auth', models.BooleanField(default=False, help_text='Whether users must be logged in to submit the form.', verbose_name='require authentication')),
                ('require_identity', models.BooleanField(default=False, help_text='Whether to collect respondent identity information.', verbose_name='require identity')),
                ('grid_columns', models.PositiveSmallIntegerField(default=1, help_text='Number of columns in the form layout grid.', verbose_name='grid columns')),
                ('workplace', models.ForeignKey(blank=True, help_text='The workplace this form belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(help_text='The uploaded file.', upload_to=lib.utils.upload.upload_to_path('forms', 'answers', 'answer.response.form.pk'), verbose_name='file')),
                ('answer', models.ForeignKey(help_text='The form answer this file belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='form.formanswer', verbose_name='answer')),
            ],
            options={
                'verbose_name': 'Form Answer File',
                'verbose_name_plural': 'Form Answer Files',
            },
        ),
        migrations.CreateModel(
            name='FormBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('time', 'Time'), ('date', 'Date'), ('file', 'File'), ('choice', 'Choice'), ('select', 'Select')], max_length=50, verbose_name='type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('config', models.JSONField(default=dict, verbose_name='configuration')),
                ('col_span', models.PositiveSmallIntegerField(default=0, verbose_name='column span')),
                ('col_start', models.PositiveSmallIntegerField(default=0, verbose_name='column start')),
                ('condition', models.JSONField(blank=True, default=dict, verbose_name='condition')),
                ('client_id', models.CharField(blank=True, default='', max_length=64, verbose_name='client id')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='form.form', verbose_name='form')),
            ],
            options={
                'verbose_name': 'Form Block',
                'verbose_name_plural': 'Form Blocks',
                'ordering': ['page__order', 'order'],
            },
        ),
        migrations.AddField(
            model_name='formanswer',
            name='block',
            field=models.ForeignKey(help_text='The form block (field) this answer is for.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.formblock', verbose_name='block'),
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Optional title shown at the top of this page.', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or instructions for this page.', verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order of this page within the form.', verbose_name='order')),
                ('form', models.ForeignKey(help_text='The form this page belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='form.form', verbose_name='form')),
            ],
            options={
                'verbose_name': 'Form Page',
                'verbose_name_plural': 'Form Pages',
                'ordering': ['order'],
                'unique_together': {('form', 'order')},
            },
        ),
        migrations.AddField(
            model_name='formblock',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='form.formpage', verbose_name='page'),
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('respondent_email', models.EmailField(blank=True, default='', help_text='The email address of the person who submitted the form.', max_length=254, verbose_name='respondent email')),
                ('respondent_phone', models.CharField(blank=True, default='', help_text='The phone number of the person who submitted the form.', max_length=20, verbose_name='respondent phone')),
                ('form', models.ForeignKey(help_text='The form that was submitted.', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='form.form', verbose_name='form')),
            ],
            options={
                'verbose_name': 'Form Response',
                'verbose_name_plural': 'Form Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formanswer',
            name='response',
            field=models.ForeignKey(help_text='The form response this answer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.formresponse', verbose_name='response'),
        ),
        migrations.AlterUniqueTogether(
            name='formblock',
            unique_together={('form', 'page', 'order')},
        ),
    ]
