# Generated by Django 6.1 on 2026-09-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('time', 'Time'), ('date', 'Date'), ('file', 'File'), ('choice', 'Choice'), ('select', 'Select'), ('content', 'Content')], max_length=50, verbose_name='type'),
        ),
    ]
