# Generated by Django 6.1 on 2026-09-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_formblock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon identifier (e.g. i-lucide-file-text) or a literal emoji character.', max_length=50, verbose_name='icon'),
        ),
    ]
