# Generated by Django 6.1 on 2026-09-13 19:39

import uuid

import django.db.models.deletion
from django.db import migrations, models

import lib.utils.upload


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0003_form_icon"),
        ("workplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormTheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cover_style",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CSS color/gradient or external image URL. Ignored when a cover file is set.",
                        max_length=500,
                        verbose_name="cover style",
                    ),
                ),
                (
                    "cover_credit",
                    models.JSONField(
                        blank=True,
                        help_text="Attribution for the cover style when its source requires it (Unsplash).",
                        null=True,
                        verbose_name="cover credit",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(help_text="The name of the theme.", max_length=255, verbose_name="name")),
                (
                    "is_preset",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a built-in theme, shared with every workplace.",
                        verbose_name="is preset",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="A background image for the public form. Takes precedence over cover_style.",
                        null=True,
                        upload_to=lib.utils.upload.upload_to_path("form-themes", "backgrounds"),
                        verbose_name="background image",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        choices=[
                            ("neutral", "Neutral"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("amber", "Amber"),
                            ("green", "Green"),
                            ("emerald", "Emerald"),
                            ("cyan", "Cyan"),
                            ("blue", "Blue"),
                            ("indigo", "Indigo"),
                            ("violet", "Violet"),
                            ("pink", "Pink"),
                        ],
                        default="neutral",
                        help_text="Accent color for buttons, links and progress indicators.",
                        max_length=20,
                        verbose_name="accent color",
                    ),
                ),
                (
                    "radius",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("sm", "Small"),
                            ("md", "Medium"),
                            ("lg", "Large"),
                            ("xl", "Extra large"),
                        ],
                        default="md",
                        help_text="Border radius applied to inputs, buttons and cards.",
                        max_length=10,
                        verbose_name="radius",
                    ),
                ),
                (
                    "input_size",
                    models.CharField(
                        choices=[("sm", "Small"), ("md", "Medium"), ("lg", "Large")],
                        default="md",
                        help_text="Size applied to inputs, selects and buttons.",
                        max_length=10,
                        verbose_name="input size",
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[("sans", "Sans-serif"), ("serif", "Serif"), ("mono", "Monospace")],
                        default="sans",
                        help_text="Font family applied to the public form.",
                        max_length=10,
                        verbose_name="font",
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Advanced CSS overrides, scoped to the public form wrapper.",
                        verbose_name="custom CSS",
                    ),
                ),
                (
                    "workplace",
                    models.ForeignKey(
                        blank=True,
                        help_text="The workplace this theme belongs to. Null for built-in presets.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_themes",
                        to="workplace.workplace",
                        verbose_name="workplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Theme",
                "verbose_name_plural": "Form Themes",
                "ordering": ["-is_preset", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="form",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="Visual theme applied to the public form.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forms",
                to="form.formtheme",
                verbose_name="theme",
            ),
        ),
    ]
