# Generated by Django 6.1 on 2026-09-17 02:39

import lib.utils.upload
from django.db import migrations, models


def move_cover_to_page(apps, schema_editor):
    """
    Covers move from Form to FormPage. Every form needs a real page-0 row to hold
    one — most forms already have one (from the editor's pagination), but a form
    that was never paginated has none yet, and its blocks sit with `page=NULL`.
    """
    Form = apps.get_model("form", "Form")
    FormPage = apps.get_model("form", "FormPage")
    FormBlock = apps.get_model("form", "FormBlock")

    for form in Form.objects.all():
        page = FormPage.objects.filter(form=form, order=0).first()
        if page is None:
            page = FormPage.objects.create(form=form, order=0)
            FormBlock.objects.filter(form=form, page__isnull=True).update(page=page)

        page.cover_image = form.cover_image
        page.cover_style = form.cover_style
        page.cover_credit = form.cover_credit
        page.save(update_fields=["cover_image", "cover_style", "cover_credit"])


def move_cover_to_form(apps, schema_editor):
    Form = apps.get_model("form", "Form")
    FormPage = apps.get_model("form", "FormPage")

    for form in Form.objects.all():
        page = FormPage.objects.filter(form=form, order=0).first()
        if page is None:
            continue

        form.cover_image = page.cover_image
        form.cover_style = page.cover_style
        form.cover_credit = page.cover_credit
        form.save(update_fields=["cover_image", "cover_style", "cover_credit"])


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_seed_form_theme_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='cover_credit',
            field=models.JSONField(blank=True, help_text='Attribution for the cover style when its source requires it (Unsplash).', null=True, verbose_name='cover credit'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='A cover image to be displayed at the top of this page.', null=True, upload_to=lib.utils.upload.upload_to_path('forms', 'covers'), verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='cover_style',
            field=models.CharField(blank=True, default='', help_text='CSS color/gradient or external image URL. Ignored when a cover file is set.', max_length=500, verbose_name='cover style'),
        ),
        migrations.RunPython(move_cover_to_page, move_cover_to_form),
        migrations.RemoveField(
            model_name='form',
            name='cover_credit',
        ),
        migrations.RemoveField(
            model_name='form',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='form',
            name='cover_style',
        ),
    ]
