# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('access_token', models.TextField(help_text='Google OAuth2 access token.', verbose_name='access token')),
                ('refresh_token', models.TextField(help_text='Google OAuth2 refresh token.', verbose_name='refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='token expires at')),
                ('folder_id', models.CharField(blank=True, help_text='Google Drive folder ID to sync from.', max_length=255, verbose_name='folder ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_connections', to=settings.AUTH_USER_MODEL, verbose_name='connected by')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_connections', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Google Drive Connection',
                'verbose_name_plural': 'Google Drive Connections',
            },
        ),
    ]
