# Generated by Django 6.1 on 2026-09-10 17:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.domains.workplace.utils.invite
import lib.utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_style', models.CharField(blank=True, default='', help_text='CSS color/gradient or external image URL. Ignored when a cover file is set.', max_length=500, verbose_name='cover style')),
                ('cover_credit', models.JSONField(blank=True, help_text='Attribution for the cover style when its source requires it (Unsplash).', null=True, verbose_name='cover credit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='The name of the workplace.', max_length=200, verbose_name='name')),
                ('slug', models.SlugField(help_text='A unique slug used in URLs.', unique=True, verbose_name='slug')),
                ('photo', models.ImageField(blank=True, help_text='The profile photo or logo for this workplace.', null=True, upload_to=lib.utils.upload.upload_to_path('workplaces', 'photos'), verbose_name='photo')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workplace is currently active.', verbose_name='is active')),
                ('invite_key', models.CharField(default=apps.domains.workplace.utils.invite.generate_invite_key, help_text='Unique key used to invite members to this workplace.', max_length=8, unique=True, verbose_name='invite key')),
                ('ai_usage_tokens', models.BigIntegerField(default=0)),
                ('ai_limit_tokens', models.BigIntegerField(default=1000000)),
            ],
            options={
                'verbose_name': 'Workplace',
                'verbose_name_plural': 'Workplaces',
            },
        ),
        migrations.CreateModel(
            name='WorkplaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('designer', 'Designer')], default='designer', help_text='The role of the member within the workplace.', max_length=10, verbose_name='role')),
                ('user', models.ForeignKey(help_text='The user who is a member of the workplace.', on_delete=django.db.models.deletion.CASCADE, related_name='workplace_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('workplace', models.ForeignKey(help_text='The workplace this member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workplace.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'abstract': False,
                'unique_together': {('workplace', 'user')},
            },
        ),
    ]
