# Generated by Django 6.1 on 2026-09-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplacemember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', help_text='Whether this membership is active or still awaiting admin approval.', max_length=10, verbose_name='status'),
        ),
    ]
